### ISSUE TITLE
师兄的前身是写php的吧？

### ISSUE THREAD

**Issue by zhao372716335** [idoubi/goz#10]
师兄的前身是写php的吧？

哈哈，一看代码格式就有一种php的感觉。

**Comment by mikemintang** [comment]
专业phper，业余gopher~

**Comment by zhao372716335** [comment]
不错，你的库包我在项目中采用了，也是phper转golang

delete 和 put，你的样式同样可以使用，和post一样，就是把请求方式post 换成delete put就可以使用了

**Comment by idoubi** [comment]
已更新版本。
