### ISSUE TITLE
简单的get方法一直超时

### ISSUE THREAD

**Issue by 309382570** [idoubi/goz#7]
只使用了
url := "http://www.baidu.com"
resp, err := req.SetUrl(url).Get()
无论url是什么都会显示
Get http://www.baidu.com: read tcp xxx.xxx.xxx.xxx: xxxx ->115.239.211.112:80: i/o timeout

**Comment by justlooks** [comment]
me too

**Comment by idoubi** [comment]
已更新版本。可以设置Timeout或者Proxy看看。
